---
title: "Tables"
output: word_document
date: "2024-01-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


|Treatment | Time|load_SRP    |Conc_Sulfide |load_Sulfide |Conc_Sulfate |load_Sulfate  |
|:---------|----:|:-----------|:------------|:------------|:------------|:-------------|
|A         |    1|0.1 ± 0.2   |NA ± NA      |NA ± NA      |1464 ± 26    |2.6 ± 4       |
|A         |    5|0.6 ± 1     |NA ± NA      |NA ± NA      |1526 ± 78    |0.7 ± 4.7     |
|A         |    8|-0.8 ± 0.3 |NA ± NA      |NA ± NA      |1467 ± 20    |0 ± 3.9       |
|A         |   11|-0.5 ± 1.1 |-2 ± 0       |0 ± 0        |1339 ± 30    |-2.1 ± 4.1    |
|A         |   13|-1.1 ± 0.4 |-2 ± 0       |0 ± 0        |1394 ± 18    |-4.3 ± 3.2    |
|A         |   18|-0.9 ± 0.4 |26 ± 24      |0.6 ± 0.5    |1388 ± 33    |-3.9 ± 3.2    |
|A         |   22|-0.6 ± 0.2 |102 ± 86     |2.1 ± 1.7    |1123 ± 44    |-8.7 ± 3.9    |
|A         |   25|-0.5 ± 0.6 |50 ± 82      |1.2 ± 1.7    |1136 ± 47    |-11.9 ± 3.3   |
|A         |   29|-0.4 ± 0.4 |39 ± 51      |1 ± 1.1      |1381 ± 53    |-15.8 ± 3.8   |
|A         |   39|0.3 ± 0.7   |168 ± 110    |3.6 ± 2.5    |1115 ± 30    |-20.7 ± 3.7   |
|A         |   42|0.4 ± 0.7   |165 ± 126    |3.7 ± 2.8    |1134 ± 40    |-23.5 ± 3.9   |
|A         |   46|0.7 ± 0.7   |234 ± 159    |5.2 ± 3.7    |1479 ± 66    |-25.5 ± 4.9   |
|A         |   56|1.2 ± 0.7   |432 ± 239    |9.4 ± 5.5    |1023 ± 61    |-34.2 ± 2.1   |
|A         |   61|1.2 ± 0.9   |277 ± 126    |6.5 ± 3.3    |966 ± 87     |-35 ± 5.1     |
|A         |   75|1.7 ± 0.6   |425 ± 121    |9.7 ± 3.3    |746 ± 23     |-39.3 ± 3.4   |
|A         |   78|1.9 ± 0.6   |466 ± 91     |10.8 ± 2.9   |703 ± 22     |-40.1 ± 3.6   |
|A         |  103|3.1 ± 0.6   |812 ± 241    |18.2 ± 6     |963 ± 25     |-51.3 ± 2.8   |
|A         |  117|3.4 ± 0.5   |553 ± 71     |13.5 ± 3.3   |758 ± 31     |-55.2 ± 3     |
|A         |  140|4.2 ± 0.5   |436 ± 91     |11.4 ± 3.1   |1002 ± 100  |-63.1 ± 1.6   |
|A         |  152|4.8 ± 0.5   |488 ± 91     |12.8 ± 3.2   |1933 ± 404  |-54.8 ± 12.2 |
|A         |  203|6.3 ± 0.4   |536 ± 62     |14.1 ± 2.6   |1103 ± 258  |-70.4 ± 7.8   |
|A         |  218|6.6 ± 0.3   |559 ± 113    |14.9 ± 3.6   |1200 ± 184  |-79 ± 7.5     |
|A         |  242|7.2 ± 0.3   |287 ± 119    |9.8 ± 3.6    |812 ± 143    |-86.5 ± 6.6   |
|B         |    1|-0.5 ± 0.3 |NA ± NA      |NA ± NA      |1398 ± 15    |0.8 ± 0.8     |
|B         |    5|-0.1 ± 0.2 |NA ± NA      |NA ± NA      |1554 ± 21    |1.4 ± 0.7     |
|B         |    8|-1.1 ± 0.6 |NA ± NA      |NA ± NA      |1478 ± 10    |0 ± 0.4       |
|B         |   11|-1.1 ± 0.5 |-2 ± 0       |0 ± 0        |1408 ± 21    |-1.1 ± 0.1    |
|B         |   13|-1.1 ± 0.5 |-2 ± 0       |0 ± 0        |1526 ± 36    |-1.4 ± 1.2    |
|B         |   18|-1.1 ± 0.5 |-2 ± 0       |0 ± 0        |1530 ± 10    |-0.8 ± 0.8    |
|B         |   22|-1.1 ± 0.5 |-2 ± 0       |0 ± 0        |1397 ± 40    |-3.4 ± 1.2    |
|B         |   25|-1.1 ± 0.5 |-2 ± 0       |0 ± 0        |1395 ± 48    |-6.6 ± 1.6    |
|B         |   29|-1.2 ± 0.5 |-2 ± 0       |0 ± 0        |1458 ± 10    |-8.3 ± 0.3    |
|B         |   39|-1.2 ± 0.5 |-2 ± 0       |0 ± 0        |1304 ± 94    |-11.6 ± 1.8   |
|B         |   42|-1.2 ± 0.5 |-2 ± 0       |0 ± 0        |1444 ± 35    |-11.2 ± 1.3   |
|B         |   46|-1.2 ± 0.5 |-2 ± 0       |0 ± 0        |1595 ± 24    |-12.6 ± 0.6   |
|B         |   56|-1.1 ± 0.5 |-2 ± 0       |0 ± 0        |1307 ± 15    |-19 ± 0.8     |
|B         |   61|-1.2 ± 0.5 |-2 ± 0       |0 ± 0        |1243 ± 23    |-20.1 ± 0.7   |
|B         |   75|-1.2 ± 0.5 |-2 ± 0       |0 ± 0        |1234 ± 68    |-19.9 ± 2     |
|B         |   78|-1.2 ± 0.5 |-2 ± 0       |0 ± 0        |1315 ± 27    |-17.5 ± 1.1   |
|B         |  103|-1.1 ± 0.6 |-2 ± 0       |0 ± 0        |1587 ± 16    |-19.6 ± 0.7   |
|B         |  117|-1.1 ± 0.6 |0 ± 0        |0 ± 0        |1520 ± 55    |-20.6 ± 1.2   |
|B         |  140|-1.1 ± 0.6 |0 ± 0        |0 ± 0        |1437 ± 6     |-22 ± 0.4     |
|B         |  152|-1.1 ± 0.5 |0 ± 0        |0 ± 0        |1545 ± 320  |-20 ± 5.4     |
|B         |  203|-0.8 ± 0.7 |0 ± 0        |0 ± 0        |1423 ± 200  |-22 ± 2.7     |
|B         |  218|-0.7 ± 0.9 |1 ± 0        |0 ± 0        |1318 ± 227  |-23.9 ± 3.4   |
|B         |  242|-1 ± 0.7    |0 ± 0        |0 ± 0        |1243 ± 200  |-25.2 ± 3     |
|C         |    1|-0.4 ± 0.4 |NA ± NA      |NA ± NA      |1329 ± 6     |0.8 ± 0.4     |
|C         |    5|-0.3 ± 0.6 |NA ± NA      |NA ± NA      |1502 ± 21    |1.7 ± 1.1     |
|C         |    8|-0.6 ± 0.1 |NA ± NA      |NA ± NA      |1384 ± 36    |-0.7 ± 0.3    |
|C         |   11|-0.7 ± 0.2 |1 ± 5        |0.1 ± 0.1    |1270 ± 27    |-3 ± 0.2      |
|C         |   13|-0.7 ± 0.2 |10 ± 21      |0.3 ± 0.5    |1342 ± 27    |-4.5 ± 0.8    |
|C         |   18|-0.6 ± 0.3 |74 ± 71      |1.9 ± 1.8    |1339 ± 53    |-4.2 ± 0.9    |
|C         |   22|-0.5 ± 0.2 |97 ± 109     |2.5 ± 2.8    |1148 ± 38    |-8.3 ± 0.5    |
|C         |   25|-0.5 ± 0.2 |188 ± 97     |4.8 ± 2.7    |1185 ± 68    |-10.8 ± 1.4   |
|C         |   29|-0.4 ± 0.2 |387 ± 160    |9.8 ± 4.5    |1427 ± 31    |-13.8 ± 0.4   |
|C         |   39|-0.4 ± 0.2 |562 ± 86     |14.3 ± 2.9   |905 ± 49     |-26 ± 1.1     |
|C         |   42|-0.4 ± 0.2 |587 ± 79     |15.3 ± 2.7   |1099 ± 11    |-24.6 ± 0.1   |
|C         |   46|-0.4 ± 0.2 |640 ± 178    |17.1 ± 5.3   |1642 ± 54    |-27.6 ± 1.9   |
|C         |   56|-0.3 ± 0.2 |1071 ± 90    |27.9 ± 3.1   |1246 ± 114  |-36.6 ± 2.6   |
|C         |   61|-0.3 ± 0.2 |711 ± 181    |20 ± 5.6     |1292 ± 64    |-35.1 ± 1.3   |
|C         |   75|-0.3 ± 0.2 |961 ± 123    |26.6 ± 4.5   |1008 ± 65    |-41.5 ± 1.4   |
|C         |   78|-0.2 ± 0.2 |1130 ± 186  |31.4 ± 6.3   |945 ± 44     |-42.9 ± 0.9   |
|C         |  103|-0.2 ± 0.2 |1332 ± 214  |37.2 ± 7.2   |1070 ± 45    |-52.4 ± 1     |
|C         |  117|-0.1 ± 0.2 |1190 ± 214  |34.6 ± 7.3   |790 ± 110    |-58.9 ± 2.4   |
|C         |  140|-0.1 ± 0.2 |1188 ± 220  |35.4 ± 7.6   |1017 ± 165  |-66.1 ± 4     |
|C         |  152|0 ± 0.3     |1164 ± 215  |35.7 ± 7.6   |1157 ± 509  |-73.2 ± 12.3 |
|C         |  203|0 ± 0.2     |1459 ± 348  |43.8 ± 11.2 |632 ± 512    |-85.4 ± 12.3 |
|C         |  218|-0.3 ± 0.7 |1455 ± 364  |44.7 ± 11.9 |977 ± 442    |-88 ± 11.2    |
|C         |  242|0 ± 0.3     |1148 ± 369  |38.3 ± 11.9 |675 ± 430    |-95.1 ± 11    |



| Depth|Treatment | Cont_S| Cont_TP| meas_S| meas_TP| theo_S| theo_TP| diff_S| diff_TP|
|-----:|:---------|------:|-------:|------:|-------:|------:|-------:|------:|-------:|
|  0.25|A         |    440|    44.0|     26|     2.6|     17|     4.8|   9.40|  -2.200|
|  0.75|A         |    360|    43.0|     25|     3.0|     19|     4.5|   6.10|  -1.400|
|  1.25|A         |    350|    49.0|     27|     3.8|     21|     5.5|   5.60|  -1.700|
|  1.75|A         |    400|    52.0|     33|     4.3|     24|     6.7|   9.50|  -2.400|
|  2.25|A         |    710|    42.0|     78|     4.7|     36|    16.0|  42.00| -11.000|
|  2.75|A         |    620|   110.0|     75|    14.0|     45|    24.0|  30.00| -10.000|
|  3.50|A         |    430|   190.0|     60|    26.0|     52|    28.0|   8.00|  -2.000|
|  4.50|A         |    360|   200.0|     56|    31.0|     58|    31.0|  -1.70|   0.250|
|  6.00|A         |    360|   200.0|     57|    32.0|     59|    31.0|  -2.00|   1.300|
|  8.00|A         |    350|   200.0|     58|    33.0|     61|    33.0|  -3.30|  -0.066|
|  0.25|B         |    380|   180.0|     36|    17.0|     35|    19.0|   0.83|  -1.400|
|  1.25|B         |    370|   200.0|     49|    26.0|     49|    26.0|  -0.52|   0.016|
|  1.75|B         |    360|   200.0|     53|    29.0|     54|    29.0|  -1.30|   0.760|
|  2.75|B         |    350|   200.0|     56|    31.0|     58|    31.0|  -2.70|   0.460|
|  3.50|B         |    360|   200.0|     57|    31.0|     59|    31.0|  -2.40|  -0.061|
|  4.50|B         |    360|   230.0|     57|    37.0|     60|    32.0|  -2.20|   4.800|
|  6.00|B         |    380|   200.0|     61|    33.0|     61|    32.0|   0.61|   0.360|
|  8.00|B         |    360|   200.0|     61|    34.0|     63|    34.0|  -1.90|   0.690|
|  0.25|C         |    490|    31.0|     30|     1.9|     13|     3.3|  17.00|  -1.400|
|  0.75|C         |    330|    33.0|     23|     2.4|     14|     3.6|   9.20|  -1.200|
|  1.25|C         |    260|    40.0|     27|     4.1|     18|     4.7|   8.10|  -0.580|
|  1.75|C         |     46|     7.8|     27|     4.7|     35|     8.8|  -7.10|  -4.000|

| Depth|Treatment | Cont_Al| Cont_Fe| Cont_Mn| Cont_Ti| rdeep_Al|   rdeep_Fe|  rdeep_Mn| rdeep_Ti|
|-----:|:---------|-------:|-------:|-------:|-------:|--------:|----------:|---------:|--------:|
|  0.25|A         |   177.2|   212.3|   17.71|   4.846|  0.09019|  0.1292000|  0.059760|  0.10670|
|  0.75|A         |   133.7|   139.5|   12.94|   3.773| -0.06676| -0.0005535| -0.008184| -0.09613|
|  1.25|A         |   158.5|   177.8|   15.88|   4.000|  0.02281|  0.0677500|  0.033660| -0.05310|
|  1.75|A         |   161.7|   212.1|   18.28|   4.774|  0.03434|  0.1288000|  0.067860|  0.09313|
|  2.25|A         |   289.8|   517.7|   45.18|   7.793|  0.49610|  0.6732000|  0.451300|  0.66350|
|  2.75|A         |   424.6|   738.3|   76.98|   9.899|  0.98200|  1.0660000|  0.904600|  1.06100|
|  3.50|A         |   444.3|   730.5|   87.60|   9.021|  1.05300|  1.0520000|  1.056000|  0.89560|
|  4.50|A         |   424.7|   730.3|   87.98|   9.229|  0.98240|  1.0520000|  1.061000|  0.93480|
|  6.00|A         |   438.5|   744.0|   87.42|   8.386|  1.03200|  1.0760000|  1.053000|  0.77550|
|  8.00|A         |   427.7|   740.7|   86.84|   9.445|  0.99290|  1.0700000|  1.045000|  0.97560|


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

| Source     | Df | Sum Sq | Mean Sq | F value | Pr(>F)  |
|------------|----|--------|---------|---------|---------|
| Treatment  | 2  | 4.21   | 2.1038  | 8.824   | 0.000215 ***
| Residuals  | 195| 46.49  | 0.2384  |         |         |

| Comparison | Difference | Lower CI    | Upper CI    | Adjusted p-value |
|------------|------------|-------------|-------------|-------------------|
| B-A        | 0.3293     | 0.1190      | 0.5396      | 0.0008331         |
| C-A        | 0.0243     | -0.1860     | 0.2346      | 0.9598566         |
| C-B        | -0.3050    | -0.5153     | -0.0947     | 0.0021698         |





|Parameter |Treatment |       total|   sdflux1|       flux|
|:---------|:---------|-----------:|---------:|----------:|
|SRP       |A         |   7.2990723| 0.2054889|  0.0092559|
|SRP       |B         |  -0.9087642| 0.0777611| -0.0111764|
|SRP       |C         |   0.0936542| 0.0423895|  0.0010338|
|Sulfate   |A         | -86.4681341| 0.4963288| -0.4886312|
|Sulfate   |B         | -25.2429647| 0.4566877| -0.1706099|
|Sulfate   |C         | -95.0540837| 0.5008871| -0.4597932|
|Sulfide   |A         |   9.8145213| 0.3624784|  0.0654716|
|Sulfide   |B         |   0.0276048| 0.0019824|  0.0001014|
|Sulfide   |C         |  38.2840629| 0.7292210|  0.2884517|


|Parameter |Treatment |      sdtot|     meantot|
|:---------|:---------|----------:|-----------:|
|SRP       |A         |  0.2863612|   7.2990723|
|SRP       |B         |  0.6624960|  -0.9087642|
|SRP       |C         |  0.2784308|   0.0936542|
|Sulfate   |A         |  6.6052898| -86.4681341|
|Sulfate   |B         |  2.9967667| -25.2429647|
|Sulfate   |C         | 11.0271803| -95.0540837|
|Sulfide   |A         |  3.5759144|   9.8145213|
|Sulfide   |B         |  0.0027902|   0.0276048|
|Sulfide   |C         | 11.8852514|  38.2840629|



| Step | Extractant                    | P fraction | P species                                         | Notes                                              |
|------|------------------------------|------------|---------------------------------------------------|-----------------------------------------------------|
| a    | MilliQ H2O                   | H2O-P      | Loosely bound P, Porewater P                      |                                                     |
| b    | 0.2% 2,2′-bipyridine + 0.1 M KCl | Bipy-P | Vivianite-P, 2,2′-bipyridine complexes with Fe(II) and releases the bound P |                                                     |
| c    | 0.11 M BD                    | BD-P       | P bound to reducible metals, e.g., Fe(III) and Mn(IV) | Dithionite reduces Fe(III) and Mn(IV) and releases the bound P |
| d    | 0.1 M NaOH                   | NaOH-P     | P bound to clay minerals                           |                                                     |
| e    | 0.5 M HCl                    | HCl-P      | Ca- and Mg-bound P                                |                                                     |
| f    | 520 ◦C ignition & 1 M HCl boiling | Residue-P | Refractory organic-P, Sludge residue after above extraction |                                                     |
| g    | 520 ◦C ignition & 1 M HCl boiling | Humic-P   | Humic acids-bound P, Precipitate from NaOH extract |                                                     |
| h    | Wet oxidation                 | Nonreactive P (nrP) | Biogenic P, e.g., organic-P, poly-P, pyro-P. Sum of the difference between TP and ortho-P in H2O-, Bipy-, BD-, and NaOH-extracts |                                                     |

|Parameter |Treatment |       sdtot|       meantot|   sdflux2|       flux|
|:---------|:---------|-----------:|-------------:|---------:|----------:|
|SRP       |A         |  14.2921386|   229.6759817| 0.0101901|  0.0272417|
|SRP       |B         |   4.6112190|     5.0005873| 0.0009967| -0.0005019|
|SRP       |C         |   4.0180521|    20.2178467| 0.0023963|  0.0050413|
|Sulfate   |A         |  76.8218684| -2443.5748509| 0.0501689| -0.5014905|
|Sulfate   |B         |  95.6969527|  -715.1096131| 0.0394507| -0.1721883|
|Sulfate   |C         | 315.6636787| -2667.9659654| 0.0465162| -0.4772312|
|Sulfide   |A         | 101.1065986|   277.4990518| 0.0305358|  0.0615416|
|Sulfide   |B         |   0.0788921|     0.7805085| 0.0001521|  0.0000972|
|Sulfide   |C         | 336.0475654|  1082.4563765| 0.1319768|  0.2753734|


|Time   |Treatment |Measurement |Type |        sd|       avg|
|:------|:---------|:-----------|:----|---------:|---------:|
|after  |A         |Total_Fe    |D    | 5.0040768| 39.104831|
|after  |A         |Total_Fe    |S    | 1.9352311| 10.353666|
|after  |A         |Total_S     |D    | 4.9400910| 15.136906|
|after  |A         |Total_S     |S    | 1.3876220| 12.393619|
|after  |A         |Total_TP    |D    | 2.0514724|  4.876472|
|after  |A         |Total_TP    |S    | 0.1254274|  1.460183|
|after  |B         |Total_Fe    |D    | 0.3394230| 42.126739|
|after  |B         |Total_Fe    |S    | 2.8564627| 36.238231|
|after  |B         |Total_S     |D    | 0.2687558| 11.578003|
|after  |B         |Total_S     |S    | 0.2930088| 11.879032|
|after  |B         |Total_TP    |D    | 0.3878349|  6.370157|
|after  |B         |Total_TP    |S    | 0.3161293|  6.035886|
|before |D         |Total_Fe    |D    | 2.2920805| 39.153902|
|before |D         |Total_S     |D    | 0.1686732| 11.922984|
|before |D         |Total_TP    |D    | 0.1349650|  6.129917|
|before |S         |Total_Fe    |S    | 0.7123793|  7.697973|
|before |S         |Total_S     |S    | 0.2539944|  8.872647|
|before |S         |Total_TP    |S    | 0.2388763|  2.283127|